version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    environment:
      DATABASE_URL: "postgres://postgres:7DLv5OzIZ0NMnAe@studi-mercadona-bdd.flycast:5432"
      MESSENGER_TRANSPORT_DSN: "doctrine://default?auto_setup=0"
 
volumes:
  database_data:
